---
title: 'Homework #2'
author: ''
date: '2019-09-20'
slug: homework-2
categories: []
tags: []
subtitle: ''
summary: 'homework#2'
authors: []
lastmod: '2019-09-20T15:51:54-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Submit homework Rmd and pdf file to: Homewor.c9u2tv5bm4mb6nbs@u.box.com

Using example data set 4 from workshop #3 (Multiple Waves, Different Variables ), to answer the following questions. There are 7 waves of data. There are five different types of repeated measures variables, all from "the Big Five" of personality. Each of these five constructs have 9 items associated with them. See codebook for more details. 


1. Create composites of each of the 5 constructs and run growth models on each of these composite constructs. Include varying intercept and slopes for each of the five models. Bonus points for doing so in purrr. Interpret the parameters for 1 of the models that you are interested in. 

2. Introduce age and sex as predictors to the slope and intercept to the same model you interpreted in #1. Interpret each of the parameters.  

3. Use the output to create a table, suitable for publication in a journal. 

4. Plot the predicted fixed effects along with the random effects on the same plot. 

5. Introduce one of the remaining 4 repeated measures as a time varying covariate (tvc) at level 1. First, run the model where the time varying covariate is constrained to be equal for everyone. Interpret the parameters of your model. 

6. Run a second tvc model where the new repeated measure is allowed to vary randomly across people. Interpret. Then compare this one with the one where it is constrained to be equal using a likelihood ratio test. Interpret.    



