---
title: 'homework #1'
author: Josh
date: '2019-09-05'
slug: homework-1
summary: "Homework #1"
categories: []
tags: []
subtitle: ''
authors: []
lastmod: '2019-09-04T13:56:17-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

 Answer the questions below using your own data (for question 1) and the dataset from this file for the remaining questions:https://raw.github.com/josh-jackson/ALDA/master/Hw1 If you have your own longitudinal data, please feel free to use that instead. 

 If using the provided dataset note that we are looking at depression across 5 waves during college. Waves are signified by a letter at the start of the variable name, starting with A, then B, then C, etcetera. Not all waves collected depression during college.  

Please email your answers via a) an Rmd file and b) a pdf to: Homewor.dk7huzwn6n5aohka@u.box.com  If you are using your own data please also attach the dataset. 


1. Create a codebook with an actual dataset you are working with (it does not need to be longitudinal). Feed it into R to change variable names. 

2. Take a wide dataset (such as the provided one) and make it long

3. Run separate linear models on all of the participants subjects (a basic regression). What is the average intercept, the average slope?  

4. Now run a mlm/lmer model with only a random intercept. What is the ICC? Interpret. 

5. Introduce a fixed slope term. What is the difference in interpretation for the fixed effects estimates in this estimate and the previous? Of the residual standard error? 

6. Run an additional model with a random slope. How does this change compare to the previous fixed slope model? Should you keep the random slope or not?  

7. Interpret the correlation between the slope and the intercept. 

8. Create a density plot of the random effects from your final model. 



 